apiVersion: jalapeno.srv6/v1
kind: PathRequest
metadata:
  name: path-request
spec:
  defaultVrf:
    ipv6:
      routes:
        - name: berlin-k8s-to-rome
          graph: ipv6_graph
          path_type: next-best-path
          same_hop_limit: 2
          plus_one_limit: 1
          source: hosts/berlin-k8s
          destination: hosts/rome
          direction: outbound